### ISSUE TITLE
Get Next Best Champ Winning Percentage and Manually Adding and Calculating Win Percentages Disagree

### ISSUE THREAD

**Issue by jordantas** [greelz/teamcomps#2]
If I select a champion (or champions) and then hit "Get Next Best Champ" we provide the next best champ based on winning percentage, for example:

![image](https://user-images.githubusercontent.com/5528618/36279199-f3028ece-125b-11e8-96c0-f281c0f02e70.png)

So, for Tristana, the system tells us Sivir is the next best champ with 32 games analyzed together and a win percentage of 65.6. However, if I add Sivir and then calculate the winning percentage I get a different result:

![image](https://user-images.githubusercontent.com/5528618/36279303-4652e52e-125c-11e8-83a3-fbd184536257.png)

**Comment by greelz** [comment]
No longer using mongo, this is no longer reproducible
