### ISSUE TITLE
Create unique key on matchwinlosseventfact

### ISSUE THREAD

**Issue by jordantas** [greelz/teamcomps#3]
We don't currently have a unique key on matchwinlosseventfact. That is actually fine, but we do need a unique index. [This](https://stackoverflow.com/questions/12125727/mysql-combined-unique-keys) StackOverflow post talks about how to do it. We should do it with: 

MatchId
IsWin
Region

OR 

MatchId
IsWin
Region
TeamCompKey (or whatever this column is called)

I don't think that we need to include patch?

**Comment by greelz** [comment]
Closing per conversation with Jordan
